### ISSUE TITLE
mpsse?

### ISSUE THREAD

**Issue by peepo** [siorpaes/iCE40prog#1]
david,

can you please supply a make file for MPSSE?

I am using ubuntu, and happily program icestick with iceprog on a regular basis,

when using ice40prog I get an error message:
MPSSE context not valid!

are you using a different protocol?

apologies for my ignorance on these matters

tx

**Comment by siorpaes** [comment]
Hello peepo,

MPSSE sources are embedded in the project and the Makefile refers to such files for building the application. Most probably the error you are experiencing is due to wrong permissions. Try launching the application as superuser. If it runs, you'll need to add udev rules to make it run also as normal users.

I will add files and relevant readme that illustrates this.

David

**Comment by peepo** [comment]
Hi David,


tried sudo same response:


file length: 104156

MPSSE context not valid!

Make sure winUSB drivers are installed with Zadig



________________________________

**Comment by siorpaes** [comment]
Hm... can you post the outcome of 'lsusb' ?

**Comment by peepo** [comment]
Bus 003 Device 092: ID 0403:6010 FTDI 2232C Dual USB-UART/FIFO IC

on another box...

**Comment by siorpaes** [comment]
which version of the programmer are you using ? the SPI version (ice40prog.c) by default targets the MPSSE cable (PID 6014) whereas the bitbanged version (ice40progbb.c) targets FTDI 2232C chip (PID 6010).

**Comment by peepo** [comment]
found alternate board 0403:6014

TBC in morning

**Comment by siorpaes** [comment]
Also, make sure all IO connections are reflecting your hardware setup. The ones defined in the sources are for the Nandland Go Board. You may need to change those mappings according to your application.

**Comment by peepo** [comment]
:6014 board

sudo ./ice40prog top_bitmap.bin
file length: 104156
Context ok
$

wfm RBGW LED marquee

however flash does not seem to store 
is upload to SRAM,
and upload to flash a work in progress?
or am I missing something?

**Comment by siorpaes** [comment]
Hi, the tool programs the SRAM only. It does not program the serial flash (yet).

**Comment by peepo** [comment]
excellent! many thanks

**Comment by siorpaes** [comment]
you'r welcome ;) let me know if you have any other inputs/suggestions
